hidden_layers = [192, 192]

rects = [
    [0, 0, 1, 1],
    [0, 0, 1, 2],
    [0, 0, 1, 3],
    [0, 0, 1, 4],
    [0, 0, 2, 1],
    [0, 0, 2, 2],
    [0, 0, 2, 3],
    [0, 0, 2, 4],
    [0, 0, 3, 1],
    [0, 0, 3, 2],
    [0, 0, 3, 3],
    [0, 0, 3, 4],
    [0, 0, 4, 1],
    [0, 0, 4, 2],
    [0, 0, 4, 3],
    [0, 0, 4, 4],
]

bounds = [0, 0, 16, 16]

packing_size_min = 3
packing_size_max = 7

learning_rate_start = 0.000005
learning_rate_end = 0.0
beta_1 = 0.5
beta_2 = 0.5

batch_size = 2048

trials = 50_00_000

future_discount = 0.75

exploit_chance_start = 0.2
exploit_chance_end = 0.3

exploit_weight = 0.0

reward_threshold_start = 0.8
reward_threshold_end = 0.9
